// <auto-generated />
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DB_Manager))]
    [Migration("20250403174324_AddQuantityToGoodsToOrder")]
    partial class AddQuantityToGoodsToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinimumPurcheQuantity")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Goods__3214EC07B40FBA6F");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("DAL.Models.GoodsToOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GoodsToO__3214EC07DBF99BF6");

                    b.HasIndex("GoodsId");

                    b.HasIndex("OrdersId");

                    b.ToTable("GoodsToOrders");
                });

            modelBuilder.Entity("DAL.Models.GoodsToSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int>("SuppliersId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GoodsToS__3214EC0740104953");

                    b.HasIndex("GoodsId");

                    b.HasIndex("SuppliersId");

                    b.ToTable("GoodsToSuppliers");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderQuantityNum")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("waiting");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07595079A9");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DAL.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Supplier__3214EC0707927B74");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DAL.Models.GoodsToOrder", b =>
                {
                    b.HasOne("DAL.Models.Good", "Goods")
                        .WithMany("GoodsToOrders")
                        .HasForeignKey("GoodsId")
                        .IsRequired()
                        .HasConstraintName("FK_GoodsToOrders_ToTable");

                    b.HasOne("DAL.Models.Order", "Orders")
                        .WithMany("GoodsToOrders")
                        .HasForeignKey("OrdersId")
                        .IsRequired()
                        .HasConstraintName("FK_GoodsToOrders_ToTable1");

                    b.Navigation("Goods");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DAL.Models.GoodsToSupplier", b =>
                {
                    b.HasOne("DAL.Models.Good", "Goods")
                        .WithMany("GoodsToSuppliers")
                        .HasForeignKey("GoodsId")
                        .IsRequired()
                        .HasConstraintName("FK_GoodsToSuppliers_ToTable_1");

                    b.HasOne("DAL.Models.Supplier", "Suppliers")
                        .WithMany("GoodsToSuppliers")
                        .HasForeignKey("SuppliersId")
                        .IsRequired()
                        .HasConstraintName("FK_GoodsToSuppliers_ToTable");

                    b.Navigation("Goods");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_ToTable");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DAL.Models.Good", b =>
                {
                    b.Navigation("GoodsToOrders");

                    b.Navigation("GoodsToSuppliers");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("GoodsToOrders");
                });

            modelBuilder.Entity("DAL.Models.Supplier", b =>
                {
                    b.Navigation("GoodsToSuppliers");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
